service: habit-quest-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  apiGateway:
    apiKeys:
      - habitQuestApiKey
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN_MINS: ${env:JWT_EXPIRES_IN_MINS}
    BASE_EXPERIENCE_POINTS: 10
    STREAK_MULTIPLIER: 0.1
    MAX_LEVEL_CAP: 100
    LEVEL_EXPERIENCE_BASE: 10
    LEVEL_EXPERIENCE_MULTIPLIER: 1.05
    MAX_EXP_PER_LEVEL: 250
  vpc:
    securityGroupIds:
      - sg-84bb0e8b
    subnetIds:
      - subnet-8c80e0ad
      - subnet-48366946
      - subnet-272d186a
      - subnet-c26f099d
      - subnet-d565cce4
      - subnet-ee335688

functions:
  api:
    handler: src/lambda.handler
    timeout: 6
    events:
      - http:
          path: /{proxy+}
          method: ANY
          private: true
          cors: true

package:
  excludeDevDependencies: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
    external: ['aws-sdk']